### ISSUE TITLE
Something is wrong.

### ISSUE THREAD

**Issue by Morritz** [Skyliegirl33/SFML_Android_Template#2] opened 2020-11-26 17:44 UTC
I compiled debug build and it runs fine on nox emulator, but it fails to open on two of my real devices.

**Comment by miyuushi** [comment] 2020-11-26 22:28
Hmm, have you checked the output of `adb logcat` or in Android Studio? That should tell you what's going on.

**Comment by Morritz** [comment] 2020-11-27 10:22
> 11-27 11:20:52.414  2806  5025 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.example.sfmltest/.MainActivity (has extras)} from uid 10027 on display 0
11-27 11:20:52.433  2806  2852 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10027)
11-27 11:20:52.464  2806  2817 I ActivityManager: Start proc 7675:com.example.sfmltest/u0a158 for activity com.example.sfmltest/.MainActivity
11-27 11:20:52.475  7675  7675 I art     : Late-enabling -Xcheck:jni
11-27 11:20:52.587  7675  7675 I LoadedApk: No resource references to update in package common
11-27 11:20:52.588  7675  7675 I LoadedApk: No resource references to update in package org.cyanogenmod.hexolibre
11-27 11:20:52.588  7675  7675 I LoadedApk: No resource references to update in package org.cyanogenmod.hexolibre
11-27 11:20:52.614  7675  7685 I art     : Background sticky concurrent mark sweep GC freed 12587(668KB) AllocSpace objects, 2(40KB) LOS objects, 44% free, 4MB/7MB, paused 5.900ms total 23.524ms
11-27 11:20:52.648  7675  7675 W linker  : /data/app/com.example.sfmltest-1/lib/arm/libopenal.so: unused DT entry: type 0xf arg 0x19ab
11-27 11:20:52.672  7675  7675 I sfml-activity: dlopen("/data/app/com.example.sfmltest-1/lib/arm/libnative-lib.so"): dlopen failed: library "libc++_shared.so" not found
11-27 11:20:52.703   422   422 I Zygote  : Process 7675 exited cleanly (1)
11-27 11:20:52.706  2806  4764 I ActivityManager: Process com.example.sfmltest (pid 7675) has died
11-27 11:20:52.706  2806  4764 D ActivityManager: cleanUpApplicationRecord -- 7675
11-27 11:20:52.719  2806  4764 I ActivityManager: Start proc 7693:com.example.sfmltest/u0a158 for activity com.example.sfmltest/.MainActivity
11-27 11:20:52.726  7693  7693 I art     : Late-enabling -Xcheck:jni
11-27 11:20:52.809  7693  7693 I LoadedApk: No resource references to update in package common
11-27 11:20:52.810  7693  7693 I LoadedApk: No resource references to update in package org.cyanogenmod.hexolibre
11-27 11:20:52.811  7693  7693 I LoadedApk: No resource references to update in package org.cyanogenmod.hexolibre
11-27 11:20:52.857  7693  7693 W linker  : /data/app/com.example.sfmltest-1/lib/arm/libopenal.so: unused DT entry: type 0xf arg 0x19ab
11-27 11:20:52.875  7693  7693 I sfml-activity: dlopen("/data/app/com.example.sfmltest-1/lib/arm/libnative-lib.so"): dlopen failed: library "libc++_shared.so" not found
11-27 11:20:52.911   422   422 I Zygote  : Process 7693 exited cleanly (1)
11-27 11:20:52.915  2806  2816 I ActivityManager: Process com.example.sfmltest (pid 7693) has died
11-27 11:20:52.915  2806  2816 D ActivityManager: cleanUpApplicationRecord -- 7693
11-27 11:20:52.927  2806  2816 I ActivityManager: Start proc 7711:com.example.sfmltest/u0a158 for activity com.example.sfmltest/.MainActivity
11-27 11:20:52.933  7711  7711 I art     : Late-enabling -Xcheck:jni
11-27 11:20:53.003  7711  7711 I LoadedApk: No resource references to update in package common
11-27 11:20:53.004  7711  7711 I LoadedApk: No resource references to update in package org.cyanogenmod.hexolibre
11-27 11:20:53.005  7711  7711 I LoadedApk: No resource references to update in package org.cyanogenmod.hexolibre
11-27 11:20:53.053  7711  7711 W linker  : /data/app/com.example.sfmltest-1/lib/arm/libopenal.so: unused DT entry: type 0xf arg 0x19ab
11-27 11:20:53.070  7711  7711 I sfml-activity: dlopen("/data/app/com.example.sfmltest-1/lib/arm/libnative-lib.so"): dlopen failed: library "libc++_shared.so" not found
11-27 11:20:53.121   422   422 I Zygote  : Process 7711 exited cleanly (1)
11-27 11:20:53.125  2806  2816 I ActivityManager: Process com.example.sfmltest (pid 7711) has died
11-27 11:20:53.125  2806  2816 D ActivityManager: cleanUpApplicationRecord -- 7711
11-27 11:20:53.126  2806  2816 W ActivityManager: Force removing ActivityRecord{22f198c u0 com.example.sfmltest/.MainActivity t172}: app died, no saved state
11-27 11:20:53.134  2806  2870 W WindowManager: Failed looking up window
11-27 11:20:53.134  2806  2870 W WindowManager: java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@e4d0e24 does not exist
11-27 11:20:53.134  2806  2870 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8821)
11-27 11:20:53.134  2806  2870 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8812)
11-27 11:20:53.134  2806  2870 W WindowManager:         at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2749)
11-27 11:20:53.134  2806  2870 W WindowManager:         at com.android.server.wm.Session.remove(Session.java:187)
11-27 11:20:53.134  2806  2870 W WindowManager:         at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3107)
11-27 11:20:53.134  2806  2870 W WindowManager:         at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5616)
11-27 11:20:53.134  2806  2870 W WindowManager:         at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3417)
11-27 11:20:53.134  2806  2870 W WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:102)
11-27 11:20:53.134  2806  2870 W WindowManager:         at android.os.Looper.loop(Looper.java:148)
11-27 11:20:53.134  2806  2870 W WindowManager:         at android.os.HandlerThread.run(HandlerThread.java:61)
11-27 11:20:53.134  2806  2870 W WindowManager:         at com.android.server.ServiceThread.run(ServiceThread.java:46)
11-27 11:20:53.164  2806  6201 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@b3855af attribute=null, token = android.os.BinderProxy@716c652

**Comment by miyuushi** [comment] 2020-11-27 10:30
`dlopen failed: library "libc++_shared.so" not found ` Well, this is the problem you're having. Try changing the CMake arguments to: `arguments "-DANDROID_ARM_NEON=TRUE", "-DANDROID_STL=c++_shared"`
If this works I'll commit the change.

**Comment by Morritz** [comment] 2020-11-27 10:37
changed app/build.gradle to this, nothing changed

**Comment by miyuushi** [comment] 2020-11-27 10:41
Okay. Inside of your NDK folder, navigate to `sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/` and make sure it contains `libc++_shared.so`

**Comment by Morritz** [comment] 2020-11-27 10:51
yeah, this file is present there

**Comment by Morritz** [comment] 2020-11-27 10:57
this file is present even in apk file

**Comment by miyuushi** [comment] 2020-11-27 11:15
Really, hmm. Strange that it supposedly can't be found. I'll take a look to see if I can reproduce it. I can confirm it works with NDK 21.1.6352462 and AS 4.1.1

**Comment by Morritz** [comment] 2020-11-27 13:40
You mean side-by-side ndk?

**Comment by Morritz** [comment] 2020-11-27 19:33
I found simple fix to this issue, although it would be good to know why it works right out of the box on your end and not on mine. Maybe we can elaborate on this topic, on other platform like discord?

**Comment by miyuushi** [comment] 2020-11-27 23:38
Sure, that's not a problem. I'd be interested to hear what fix you found.

**Comment by miyuushi** [comment] 2021-01-16 01:05
Going to close this issue since you seem to have fixed it.

**Closed as completed by miyuushi** 2021-01-16 01:05 UTC
